[project]
name = "12-project-feedback-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Lochan Singoria", email = "lochansingoria@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
12-project-feedback-analyzer = "12_project_feedback_analyzer:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
